In [14]:
from bayes import *
import numpy as np

In [2]:
listPosts, listClasses = loadDataSet()

In [3]:
listPosts

[['my', 'dog', 'has', 'flea', 'problem', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthing', 'dog', 'food', 'stupid']]

In [4]:
listClasses

[0, 1, 0, 1, 0, 1]

In [5]:
myVocabList = createVocabList(listPosts)

In [6]:
myVocabList

['so',
 'how',
 'help',
 'steak',
 'mr',
 'buying',
 'licks',
 'has',
 'I',
 'ate',
 'stop',
 'my',
 'love',
 'not',
 'him',
 'worthing',
 'park',
 'flea',
 'problem',
 'cute',
 'is',
 'garbage',
 'take',
 'stupid',
 'dalmation',
 'food',
 'posting',
 'quit',
 'to',
 'please',
 'maybe',
 'worthless',
 'dog']

In [10]:
myVocabList.count

<function list.count>

In [12]:
len(myVocabList)

33

In [15]:
np.array(listPosts)

array([list(['my', 'dog', 'has', 'flea', 'problem', 'help', 'please']),
       list(['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid']),
       list(['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him']),
       list(['stop', 'posting', 'stupid', 'worthless', 'garbage']),
       list(['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him']),
       list(['quit', 'buying', 'worthing', 'dog', 'food', 'stupid'])], dtype=object)

In [16]:
np.array(listPosts)[0]

['my', 'dog', 'has', 'flea', 'problem', 'help', 'please']

In [17]:
np.matrix(listPosts)

matrix([[list(['my', 'dog', 'has', 'flea', 'problem', 'help', 'please']),
         list(['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid']),
         list(['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him']),
         list(['stop', 'posting', 'stupid', 'worthless', 'garbage']),
         list(['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him']),
         list(['quit', 'buying', 'worthing', 'dog', 'food', 'stupid'])]], dtype=object)

In [18]:
d1 = np.array(listPosts)

In [19]:
d1

array([list(['my', 'dog', 'has', 'flea', 'problem', 'help', 'please']),
       list(['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid']),
       list(['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him']),
       list(['stop', 'posting', 'stupid', 'worthless', 'garbage']),
       list(['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him']),
       list(['quit', 'buying', 'worthing', 'dog', 'food', 'stupid'])], dtype=object)

In [20]:
print(d1)

[list(['my', 'dog', 'has', 'flea', 'problem', 'help', 'please'])
 list(['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'])
 list(['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'])
 list(['stop', 'posting', 'stupid', 'worthless', 'garbage'])
 list(['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'])
 list(['quit', 'buying', 'worthing', 'dog', 'food', 'stupid'])]


In [21]:
d2 = np.array((3,4))

In [22]:
d2

array([3, 4])

In [24]:
d2 = np.array(np.arange(10).reshape(2,5))

In [25]:
d2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
d2[0]

array([0, 1, 2, 3, 4])

In [41]:
d3 = np.array([[[1,3,4], [2,7,6,8],[2,3,4]]])

In [42]:
d3

array([[list([1, 3, 4]), list([2, 7, 6, 8]), list([2, 3, 4])]], dtype=object)

In [43]:
d3[0]

array([list([1, 3, 4]), list([2, 7, 6, 8]), list([2, 3, 4])], dtype=object)

In [40]:
d4 = np.array([listPosts])

In [31]:
d4

array([[list(['my', 'dog', 'has', 'flea', 'problem', 'help', 'please']),
        list(['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid']),
        list(['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him']),
        list(['stop', 'posting', 'stupid', 'worthless', 'garbage']),
        list(['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him']),
        list(['quit', 'buying', 'worthing', 'dog', 'food', 'stupid'])]], dtype=object)

In [32]:
listPosts

[['my', 'dog', 'has', 'flea', 'problem', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthing', 'dog', 'food', 'stupid']]

In [52]:
d4[0]

array([list(['my', 'dog', 'has', 'flea', 'problem', 'help', 'please']),
       list(['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid']),
       list(['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him']),
       list(['stop', 'posting', 'stupid', 'worthless', 'garbage']),
       list(['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him']),
       list(['quit', 'buying', 'worthing', 'dog', 'food', 'stupid'])], dtype=object)

In [50]:
sum(d4[0])

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [51]:
listPosts[0]

['my', 'dog', 'has', 'flea', 'problem', 'help', 'please']

In [49]:
sum(listPosts[0])

TypeError: unsupported operand type(s) for +: 'int' and 'str'