In [215]:
# -*- coding: utf-8 -*-
from numpy import *
from bayes import *
import os

In [2]:
listOPosts, listClasses = loadDataSet()

In [3]:
listOPosts

[['my', 'dog', 'has', 'flea', 'problem', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthing', 'dog', 'food', 'stupid']]

In [4]:
listClasses

[0, 1, 0, 1, 0, 1]

In [5]:
myVocabList = createVocabList(listOPosts)

In [6]:
myVocabList

['stupid',
 'ate',
 'has',
 'help',
 'him',
 'dalmation',
 'so',
 'stop',
 'food',
 'quit',
 'love',
 'flea',
 'mr',
 'licks',
 'buying',
 'not',
 'park',
 'worthless',
 'is',
 'please',
 'steak',
 'problem',
 'how',
 'take',
 'garbage',
 'posting',
 'cute',
 'maybe',
 'to',
 'worthing',
 'my',
 'I',
 'dog']

In [14]:
len(myVocabList)

33

In [7]:
trainMat = []

In [8]:
for postinDoc in listOPosts:
    trainMat.append(setOfWords2Vec(myVocabList, postinDoc))

In [10]:
type(trainMat)

list

In [12]:
ab = array(trainMat)

In [13]:
ab

array([[0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]])

In [15]:
len(ab[0])

33

In [16]:
ab.shape

(6, 33)

In [32]:
array(trainMat), listClasses

(array([[0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
        [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
         0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
         0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0],
        [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
         1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]]), [0, 1, 0, 1, 0, 1])

In [38]:
def trainNB0(trainMatrix, trainCategory):
    numTrainDocs = len(trainMatrix)
    numWords = len(trainMatrix[0])
    pAbusive = sum(trainCategory) / float(numTrainDocs)        # P(1)的概率，为二分类问题，则有P(0) = 1 - P(1)
    p0Num = ones(numWords)
    p1Num = ones(numWords)
    p0Denom = 2.0
    p1Denom = 2.0
    for i in range(numTrainDocs):
        if trainCategory[i] ==1:
            p1Num += trainMatrix[i]
            p1Denom += sum(trainMatrix[i])
        else:
            p0Num += trainMatrix[i]
            p0Denom += sum(trainMatrix[i])
    p1Vect = log(p1Num / p1Denom)
    p0Vect = log(p0Num / p0Denom)
    return p0Vect, p1Vect, pAbusive

In [39]:
p0V, p1V, pAb = trainNB0(trainMat, listClasses)

In [40]:
p0V

array([-3.25809654, -2.56494936, -2.56494936, -2.56494936, -2.15948425,
       -2.56494936, -2.56494936, -2.56494936, -3.25809654, -3.25809654,
       -2.56494936, -2.56494936, -2.56494936, -2.56494936, -3.25809654,
       -3.25809654, -3.25809654, -3.25809654, -2.56494936, -2.56494936,
       -2.56494936, -2.56494936, -2.56494936, -3.25809654, -3.25809654,
       -3.25809654, -2.56494936, -3.25809654, -2.56494936, -3.25809654,
       -1.87180218, -2.56494936, -2.56494936])

In [41]:
p1V

array([-1.65822808, -3.04452244, -3.04452244, -3.04452244, -2.35137526,
       -3.04452244, -3.04452244, -2.35137526, -2.35137526, -2.35137526,
       -3.04452244, -3.04452244, -3.04452244, -3.04452244, -2.35137526,
       -2.35137526, -2.35137526, -2.35137526, -3.04452244, -3.04452244,
       -3.04452244, -3.04452244, -3.04452244, -2.35137526, -2.35137526,
       -2.35137526, -3.04452244, -2.35137526, -2.35137526, -2.35137526,
       -3.04452244, -3.04452244, -1.94591015])

In [43]:
pAb

0.5

In [37]:
p0V, p1V, pAb = trainNB0(trainMat, listClasses)

7.0
8.0
15.0
13.0
24.0
19.0
19.0 24.0


In [46]:
def classifyNB(vec2Classify, p0Vec, p1Vec, pClass1):
    p1 = sum(vec2Classify * p1Vec) + log(pClass1)
    p0 = sum(vec2Classify * p0Vec) + (1 - log(pClass1))
    if  p1 > p0:
        return 1
    else:
        return 0
    
def testingNB():
    listOPosts, listClasses = loadDataSet()
    myVocabList = createVocabList(listOPosts)
    trainMat = []
    for postinDoc in listOPosts:
        trainMat.append(setOfWords2Vec(myVocabList, postinDoc))
    p0V, p1V, pAb = trainNB0(array(trainMat), array(listClasses))
    testEntry = ['love', 'my', 'dalmation']
    thisDoc = array(setOfWords2Vec(myVocabList, testEntry))
    print(testEntry, 'classified as:', classifyNB(thisDoc, p0V, p1V, pAb))
    testEntry = ['stupid', 'garbage']
    thisDoc = array(setOfWords2Vec(myVocabList, testEntry))
    print(testEntry, 'classified as:', classifyNB(thisDoc, p0V, p1V, pAb))

In [48]:
testingNB()

['love', 'my', 'dalmation'] classified as: 0
['stupid', 'garbage'] classified as: 1


In [190]:
def texParse(bigString):
    import re
    listOfTokens = re.split(r'\W*', bigString)
    return [tok.lower() for tok in listOfTokens if len(tok) > 2]

In [51]:
texParse('D:\Projects_Python\DataSets\machinelearninginaction\Ch04\email\ham\6.txt')

D:\Program Files (x86)\Anaconda3\envs\tensorflow\lib\re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)


[]

In [52]:
print('D:\Projects_Python\DataSets\machinelearninginaction\Ch04\email\ham\6.txt')

D:\Projects_Python\DataSets\machinelearninginaction\Ch04\email\ham.txt


In [71]:
fr = open('6.txt','r')
line = []
for li in fr:
    line.append(line)
fr.close
print(line)
# print(fr.readlines)
# print( line for line in fr.readlines)

[[...], [...], [...], [...], [...], [...], [...]]


In [72]:
line

[[...], [...], [...], [...], [...], [...], [...]]

In [73]:
fr

<_io.TextIOWrapper name='6.txt' mode='r' encoding='cp936'>

In [74]:
fr.readlines()

[]

In [75]:
fr = open('6.txt')

In [76]:
fr.readlines

<function TextIOWrapper.readlines>

In [77]:
fr.readlines()

['Hello,\n',
 '\n',
 'Since you are an owner of at least one Google Groups group that uses the customized welcome message, pages or files, we are writing to inform you that we will no longer be supporting these features starting February 2011. We made this decision so that we can focus on improving the core functionalities of Google Groups -- mailing lists and forum discussions.  Instead of these features, we encourage you to use products that are designed specifically for file storage and page creation, such as Google Docs and Google Sites.\n',
 '\n',
 'For example, you can easily create your pages on Google Sites and share the site (http://www.google.com/support/sites/bin/answer.py?hl=en&answer=174623) with the members of your group. You can also store your files on the site by attaching files to pages (http://www.google.com/support/sites/bin/answer.py?hl=en&answer=90563) on the site. If you抮e just looking for a place to upload your files so that your group members can download them,

In [191]:
import re
regEx = re.compile('\\W*')
fr = open('6.txt')
list1 = []
l4 = fr.read()
print(l4, type(l4))
for line in fr.readlines():
    line = line.split()
#     line = regEx.split(line)
    list1 += (line)
L3 = fr.read()
l2 = texParse(l4)
fr.close()
# [tok.lower() for tok in list1 if len(tok) > 2]

Hello,

Since you are an owner of at least one Google Groups group that uses the customized welcome message, pages or files, we are writing to inform you that we will no longer be supporting these features starting February 2011. We made this decision so that we can focus on improving the core functionalities of Google Groups -- mailing lists and forum discussions.  Instead of these features, we encourage you to use products that are designed specifically for file storage and page creation, such as Google Docs and Google Sites.

For example, you can easily create your pages on Google Sites and share the site (http://www.google.com/support/sites/bin/answer.py?hl=en&answer=174623) with the members of your group. You can also store your files on the site by attaching files to pages (http://www.google.com/support/sites/bin/answer.py?hl=en&answer=90563) on the site. If you抮e just looking for a place to upload your files so that your group members can download them, we suggest you try Google

D:\Program Files (x86)\Anaconda3\envs\tensorflow\lib\re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)


[]

In [107]:
emailText = open('6.txt').read()
listOfTokens = regEx.split(emailText)

D:\Program Files (x86)\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: split() requires a non-empty pattern match.
  


In [108]:
emailText

'Hello,\n\nSince you are an owner of at least one Google Groups group that uses the customized welcome message, pages or files, we are writing to inform you that we will no longer be supporting these features starting February 2011. We made this decision so that we can focus on improving the core functionalities of Google Groups -- mailing lists and forum discussions.  Instead of these features, we encourage you to use products that are designed specifically for file storage and page creation, such as Google Docs and Google Sites.\n\nFor example, you can easily create your pages on Google Sites and share the site (http://www.google.com/support/sites/bin/answer.py?hl=en&answer=174623) with the members of your group. You can also store your files on the site by attaching files to pages (http://www.google.com/support/sites/bin/answer.py?hl=en&answer=90563) on the site. If you抮e just looking for a place to upload your files so that your group members can download them, we suggest you try G

In [109]:
listOfTokens

['Hello',
 'Since',
 'you',
 'are',
 'an',
 'owner',
 'of',
 'at',
 'least',
 'one',
 'Google',
 'Groups',
 'group',
 'that',
 'uses',
 'the',
 'customized',
 'welcome',
 'message',
 'pages',
 'or',
 'files',
 'we',
 'are',
 'writing',
 'to',
 'inform',
 'you',
 'that',
 'we',
 'will',
 'no',
 'longer',
 'be',
 'supporting',
 'these',
 'features',
 'starting',
 'February',
 '2011',
 'We',
 'made',
 'this',
 'decision',
 'so',
 'that',
 'we',
 'can',
 'focus',
 'on',
 'improving',
 'the',
 'core',
 'functionalities',
 'of',
 'Google',
 'Groups',
 'mailing',
 'lists',
 'and',
 'forum',
 'discussions',
 'Instead',
 'of',
 'these',
 'features',
 'we',
 'encourage',
 'you',
 'to',
 'use',
 'products',
 'that',
 'are',
 'designed',
 'specifically',
 'for',
 'file',
 'storage',
 'and',
 'page',
 'creation',
 'such',
 'as',
 'Google',
 'Docs',
 'and',
 'Google',
 'Sites',
 'For',
 'example',
 'you',
 'can',
 'easily',
 'create',
 'your',
 'pages',
 'on',
 'Google',
 'Sites',
 'and',
 'share',


In [198]:
int(random.uniform(0, 35))

31

In [202]:
trainingSet = range(50)[29]

In [204]:
print(trainingSet)

29


In [205]:
range(50)

range(0, 50)

In [206]:
l = range(50)

In [207]:
l

range(0, 50)

In [208]:
l[28]

28

In [221]:
path1 = 'D:\Projects_Python\DataSets\machinelearninginaction\Ch04\email\spam'
path2 = 'D:\Projects_Python\DataSets\machinelearninginaction\Ch04\email\ham'

def spamTest():
    numdir = len(os.listdir(path1))
    docList = []
    classList = []
    fullText = []
    for i in range(1, numdir):
        wordList = texParse(open(path1 + '\%d.txt' % i).read())    # 某一文档的字符列表
        docList.append(wordList)                  # 将所得字符列表按列表形式存放到docListzhong
        fullText.extend(wordList)                 # 将所得字符列表按字符形式存放到fullText中
        classList.append(1)
        wordList = texParse(open(path2 + '\%d.txt' % i).read())
        docList.append(wordList)
        fullText.extend(wordList)
        classList.append(0)
    vocabList = createVocabList(docList)           # docList为整个文档（全部邮件），文档每行为一份邮件中的全部字符,
                                                   # 同时将整个文档中出现的字符整理为一个字符向量
    trainingSet = range(50)
    # ********随机选择测试集*******
    testSet = []
    for i in range(10):
        randIndex = int(random.uniform(0, len(trainingSet)))
        testSet.append(trainingSet[randIndex])
        del(trainingSet[randIndex])
    ## *******随机选取训练集*******
    trainMat = []
    trainClasses = []
    for docIndex in trainingSet:
        trainMat.append(setOfWords2Vec(vocabList, docList[docIndex]))
        trainClasses.append(classList[docIndex])
    poV, p1V, pSpam = trainNB0(array(trainMat), array(trainClasses))
    errorCount = 0
    for docIndex in testSet:
        wordVector = setOfWords2Vec(vocabList, docList[docIndex])
        if classifyNB(array(wordVector), p0V, p1V, pSpam) != classList[docIndex]:
            errorCount += 1
    print('the error rate is :', float(errorCount) / len(testSet))

In [222]:
spamTest()

D:\Program Files (x86)\Anaconda3\envs\tensorflow\lib\re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)


UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 199: illegal multibyte sequence